---
title: 'Peer-graded Assignment: Course Project 2'
author: "Abhishek Kumar"
date: "16 July 2020"
output: html_document
---

Exploratory Data Analysis with NOAA storm data
================================================

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Synopsis

Storms and other severe weather events can cause both public health and economic 
problems for communities and municipalities. Many severe events can result in 
fatalities, injuries, and property damage, and preventing such outcomes to the 
extent possible is a key concern.

### Data
This analysis involves an exploration of the U.S. National Oceanic and Atmospheric 
Administration's (NOAA) storm database. This data is available in the form of a 
comma-separated-value file compressed via the bzip2 algorithm to reduce its size. 
This data can be downloaded from the following link:

 * [Storm Data](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2) [47Mb]

The documentation on how some of the variables are constructed/defined for the 
database is available from below links: 

 * National Weather Service [Storm Data Documentation](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf)

 * National Climatic Data Center Storm Events [FAQ](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf)

This database tracks characteristics of major storms and weather events in the 
United States, including when and where they occur, as well as estimates of any 
fatalities, injuries, and property damage. The events in the database start in the 
year 1950 and end in November 2011. In the earlier years of the database there 
are generally fewer events recorded, most likely due to a lack of good records. 
More recent years should be considered more complete.

# Data Processing

start from the raw data file (i.e. the original .csv.bz2 file)

describes how the data were loaded into R and processed for analysis

 *  how the data were loaded into R and processed for analysis

In particular, your analysis must start from the raw CSV file containing the 
data. You cannot do any preprocessing outside the document. If preprocessing is 
time-consuming you may consider using the `cache = TRUE` option for certain 
code chunks.

# Results

figure in the document that contains a plot

 * figure(s) have descriptive captions (i.e. there is a description near the 
 * figure of what is happening in the figure)
 * Your analysis must have no more than three figures. 
 * Figures may have multiple plots in them (i.e. panel plots), but there cannot 
 be more than three figures total.

1. which types of events are most harmful to population health?

2. which types of events have the greatest economic consequences?

Questions
Your data analysis must address the following questions:

 * Across the United States, which types of events (as indicated in the `EVTYPE` 
variable) are most harmful with respect to population health?

 * Across the United States, which types of events have the greatest economic 
 consequences?

Consider writing your report as if it were to be read by a government or 
municipal manager who might be responsible for preparing for severe weather 
events and will need to prioritize resources for different types of events. 
However, there is no need to make any specific recommendations in your report.

